Add better control on manual builds

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -5,7 +5,9 @@ on:
     branches:
       # Push events on develop branch
       - develop
-  workflow_dispatch:    # Used to trigger from parent projects
+  workflow_dispatch:    # Used to trigger from parent projects and manually
+    branches:
+      - develop
 
 env:
   DISPLAY_CONTEXT: ${{ secrets.DISPLAY_CONTEXT }}    # To display github context for debugging
@@ -20,6 +22,17 @@ jobs:
       PHASE_ID: x
 
     steps:
+      - name: Set branch name from github reference
+        run: |
+          BRANCH_NAME=`basename ${{ github.ref }}`
+          if [[ ${BRANCH_NAME} == develop ]]; then
+            echo "BRANCH_NAME: ${BRANCH_NAME}"
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          else
+            echo "Error - Must use the develop branch"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v2
 
@@ -47,12 +60,6 @@ jobs:
           echo "STEPS CONTEXT:"
           echo
           echo "$STEPS_CONTEXT"
-
-      - name: Set branch name from github reference
-        run: |
-          BRANCH_NAME=`basename ${{ github.ref }}`
-          echo "BRANCH_NAME: ${BRANCH_NAME}"
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
 
 #      - name: Download artifacts from steves-test-repo
 #        uses: aochmann/actions-download-artifact@1.0.4
diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -2,10 +2,10 @@ name: Manual build
 
 on: 
   workflow_dispatch:
-    branches:
-      - develop
-      - 'feature/**'
-      - '*feature*'
+#    branches:
+#      - develop
+#      - 'feature/**'
+#      - '*feature*'
 #    branches-ignore:
 #      - 'release_v*'
 #      - 'release/release_v*'
@@ -43,13 +43,18 @@ jobs:
         run: |
           BRANCH_NAME=`basename ${{ github.ref }}`
           if [[ ${BRANCH_NAME} == *'release_v'* ]]; then
+            echo "Error - Do not use a release branch!"
             exit 1
+          elif [[ ${BRANCH_NAME} == develop ]]; then
+            echo "Error - Do not use the develop branch!"
+            exit 1
+          else 
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+            LIB_BRANCH=`echo ${{ github.event.inputs.LIB_BRANCH }} | tr "/" "-"`
+            echo "LIB_BRANCH=${LIB_BRANCH}" >> $GITHUB_ENV
+            echo "BRANCH_NAME:${BRANCH_NAME}"
+            echo "LIB_BRANCH:${LIB_BRANCH}"
           fi
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
-          LIB_BRANCH=`echo ${{ github.event.inputs.LIB_BRANCH }} | tr "/" "-"`
-          echo "LIB_BRANCH=${LIB_BRANCH}" >> $GITHUB_ENV
-          echo "BRANCH_NAME:${BRANCH_NAME}"
-          echo "LIB_BRANCH:${LIB_BRANCH}"
 
       - name: Checkout code
         uses: actions/checkout@v2
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,7 +6,10 @@ on:
       # Push events on release branches
       - 'release_v*'
       - 'release/release_v*'
-  workflow_dispatch:    # Used to trigger from parent projects
+  workflow_dispatch:    # Used to trigger from parent projects and manually
+    branches:
+      - 'release_v*'
+      - 'release/release_v*'
 
 env:
   DISPLAY_CONTEXT: ${{ secrets.DISPLAY_CONTEXT }}    # To display github context for debugging
@@ -21,6 +24,17 @@ jobs:
       PHASE_ID: b
 
     steps:
+      - name: Set branch name from github reference
+        run: |
+          BRANCH_NAME=`basename ${{ github.ref }}`
+          if [[ ${BRANCH_NAME} == *'release_v'* ]]; then
+            echo "BRANCH_NAME: ${BRANCH_NAME}"
+            echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+          else
+            echo "ERROR - Not a release branch"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v2
 
@@ -48,12 +62,6 @@ jobs:
           echo "STEPS CONTEXT:"
           echo
           echo "$STEPS_CONTEXT"
-
-      - name: Set branch name from github reference
-        run: |
-          BRANCH_NAME=`basename ${{ github.ref }}`
-          echo "BRANCH_NAME: ${BRANCH_NAME}"
-          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
 
 #      - name: Download artifacts from steves-test-repo
 #        uses: aochmann/actions-download-artifact@1.0.4
